version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db-data:/var/lib/mysql
  auction-app:
    build: .
    depends_on:
      - mysqldb
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "server.port" : "8765",
        "spring.jpa.show-sql" : "true",
        "spring.datasource.driverClassName" : "com.mysql.cj.jdbc.Driver",
        "spring.jpa.defer-datasource-initialization" : "true",
        "spring.sql.init.mode" : "always"
      }'

volumes:
  db-data: